#!/usr/bin/make -f
#
# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0
#

include_guard = set
scanner = git-repo-scanner
custom_scanner = set

include ../../scanners.mk

# Uncomment overwrite to run the tests locally
integration-tests:
	@echo ".: 🚨⏭ Skipped as are too flaky because of github rate limits to run in CI."